### ISSUE TITLE
Современная пагинация

### ISSUE THREAD

**Issue by Y4r0z** [EtoZheSandy/L4D4_VueNuxt#4]
Стоит добавить фреймворк для плавной пагинации рейтинга, чтобы каждый раз не нажимать "Загрузить еще"

**Comment by EtoZheSandy** [comment]
Касательно пагинации по топ игроков - это не особо важная ведь, всем
интересно первые 20-30 а после люди предпочитают вписать ник для поиска
(проверено по соц опросами ООО Сэнди)
Про пикчи не уверен, у меня даже с моб инета норм грузят, они же стимовские
и уже пережатые очень хорошо

пн, 19 февр. 2024 г., 23:52 Y4r0z ***@***.***>:
